// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Travail1_Partie_4.Models;

public partial class Bd_ReseauContext : DbContext
{
    public Bd_ReseauContext()
    {
    }

    public Bd_ReseauContext(DbContextOptions<Bd_ReseauContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TblCompagnie> TblCompagnies { get; set; }

    public virtual DbSet<TblEmployee> TblEmployees { get; set; }

    public virtual DbSet<TblImpute> TblImputes { get; set; }

    public virtual DbSet<TblPiece> TblPieces { get; set; }

    public virtual DbSet<TblProjet> TblProjets { get; set; }

    public virtual DbSet<TblStock> TblStocks { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=bd-tinfo;Initial Catalog=Bd_Reseau;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TblCompagnie>(entity =>
        {
            entity.HasKey(e => e.IdCompagnie).HasName("PK__tbl_comp__517CB383462BDFD9");
        });

        modelBuilder.Entity<TblEmployee>(entity =>
        {
            entity.HasKey(e => e.IdEmployee).HasName("PK__tbl_empl__F807679C12553400");
        });

        modelBuilder.Entity<TblImpute>(entity =>
        {
            entity.HasKey(e => e.IdImpute).HasName("PK__tbl_impu__AD6F00C071179166");

            entity.HasOne(d => d.IdEmployeeNavigation).WithMany(p => p.TblImputes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_impute_employee");

            entity.HasOne(d => d.IdStockNavigation).WithMany(p => p.TblImputes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_impute_stock");
        });

        modelBuilder.Entity<TblPiece>(entity =>
        {
            entity.HasKey(e => e.IdPiece).HasName("PK__tbl_piec__D20D1E0A21F31439");
        });

        modelBuilder.Entity<TblProjet>(entity =>
        {
            entity.HasKey(e => e.IdProjet).HasName("PK__tbl_proj__36C5661D20DFB84E");

            entity.HasOne(d => d.IdCompagnieNavigation).WithMany(p => p.TblProjets)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tbl_proje__id_co__4316F928");
        });

        modelBuilder.Entity<TblStock>(entity =>
        {
            entity.HasKey(e => e.IdStock).HasName("PK__tbl_stoc__3A39590A54B5FC4D");

            entity.HasOne(d => d.IdPieceNavigation).WithMany(p => p.TblStocks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tbl_stock__id_pi__48CFD27E");

            entity.HasOne(d => d.IdProjetNavigation).WithMany(p => p.TblStocks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tbl_stock__id_pr__49C3F6B7");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}