// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travail1_Partie_4.Models;

[Table("tbl_employee")]
[Index("Email", Name = "UQ_email", IsUnique = true)]
public partial class TblEmployee
{
    [Key]
    [Column("id_employee")]
    public int IdEmployee { get; set; }

    [Column("nom")]
    [StringLength(200)]
    public string Nom { get; set; }

    [Column("prenom")]
    [StringLength(200)]
    public string Prenom { get; set; }

    [Required]
    [Column("email")]
    [StringLength(200)]
    public string Email { get; set; }

    [InverseProperty("IdEmployeeNavigation")]
    public virtual ICollection<TblImpute> TblImputes { get; set; } = new List<TblImpute>();
}