// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travail1_Partie_4.Models;

[Table("tbl_impute")]
public partial class TblImpute
{
    [Key]
    [Column("id_impute")]
    public int IdImpute { get; set; }

    [Column("id_employee")]
    public int IdEmployee { get; set; }

    [Column("id_stock")]
    public int IdStock { get; set; }

    [Column("quantite_impute")]
    public int? QuantiteImpute { get; set; }

    [Column("date_imputee", TypeName = "date")]
    public DateTime? DateImputee { get; set; }

    [ForeignKey("IdEmployee")]
    [InverseProperty("TblImputes")]
    public virtual TblEmployee IdEmployeeNavigation { get; set; }

    [ForeignKey("IdStock")]
    [InverseProperty("TblImputes")]
    public virtual TblStock IdStockNavigation { get; set; }
}