// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travail1_Partie_4.Models;

[Table("tbl_piece")]
[Index("NumeroIndustrie", Name = "UQ__tbl_piec__2742638FB788A67D", IsUnique = true)]
public partial class TblPiece
{
    [Key]
    [Column("id_piece")]
    public int IdPiece { get; set; }

    [Column("description")]
    [StringLength(200)]
    public string Description { get; set; }

    [Column("numeroIndustrie")]
    [StringLength(200)]
    public string NumeroIndustrie { get; set; }

    [InverseProperty("IdPieceNavigation")]
    public virtual ICollection<TblStock> TblStocks { get; set; } = new List<TblStock>();
}