// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travail1_Partie_4.Models;

[Table("tbl_stock")]
[Index("IdPiece", "IdProjet", Name = "UQ_projetPiece", IsUnique = true)]
public partial class TblStock
{
    [Key]
    [Column("id_stock")]
    public int IdStock { get; set; }

    [Column("quantite_stock")]
    public int? QuantiteStock { get; set; }

    [Column("quantite_prevu")]
    public int? QuantitePrevu { get; set; }

    [Column("id_piece")]
    public int IdPiece { get; set; }

    [Column("id_projet")]
    public int IdProjet { get; set; }

    [ForeignKey("IdPiece")]
    [InverseProperty("TblStocks")]
    public virtual TblPiece IdPieceNavigation { get; set; }

    [ForeignKey("IdProjet")]
    [InverseProperty("TblStocks")]
    public virtual TblProjet IdProjetNavigation { get; set; }

    [InverseProperty("IdStockNavigation")]
    public virtual ICollection<TblImpute> TblImputes { get; set; } = new List<TblImpute>();
}